### ISSUE TITLE
support for docker exec or SSH connectivity

### ISSUE THREAD

**Issue by aabs** [tutumcloud/tutum-cli#53]
The CLI could benefit from a way to exec a command against a container.  I suppose it could look like this:

    tutum container exec 7eaf7fff rm /install

Another alternative might just be to provide SSH:

    tutum container ssh 7eaf7fff

Allowing one to just manually run whatever commands the API does not currently support.

**Comment by tifayuki** [comment]
`tutum exec` has been supported
`tutum ssh` is in progress
