### ISSUE TITLE
[BUG] Server Error: Post https://tutum.co/v1/users/

### ISSUE THREAD

**Issue by revett** [tutumcloud/tutum-cli#56]
I get the following error message intermittently when pushing an image to my Tutum private registry.

**Command**:

    tutum image push revett/my-image

**Error message**:

    500 Server Error: Internal Server Error ("Server Error: Post https://tutum.co/v1/users/: EOF")

**Comment by tifayuki** [comment]
`tutum image push` call docker api to push the image to push to tutum registery.
Can you please try to use `docker push` to see if you get the similar error?
If yes, this might be an issue of our registry or network connectivity.

**Comment by fortis** [comment]
I have that problem too.

> tutum login
- ok
> tutum image push ticketpayweb/nginx-drupal
500 Server Error: Internal Server Error ("invalid registry endpoint https://tutum.co/v1/: Get https://tutum.co/v1/_ping: dial tcp: i/o timeout. If this private registry supports only HTTP or HTTPS with an unknown CA certificate, please add `--insecure-registry tutum.co` to the daemon's arguments. In the case of HTTPS, if you have access to the registry's CA certificate, no need for the flag; simply place the CA certificate at /etc/docker/certs.d/tutum.co/ca.crt")
---

and with docker:
> docker login tutum.co
Username: fortis
Password:
Email: xxx@xxx.xxx

FATA[0028] Error response from daemon: v1 ping attempt failed with error: Get http://tutum.co/v1/_ping: dial tcp: i/o timeout

**Comment by fortis** [comment]
I tried to login in VM with boot2docker shh, and then add line:
EXTRA_ARGS="--insecure-registry tutum.co"

to /var/lib/boot2docker/profile
and then I called boot2docker restart but that doesn't helped

**Comment by fermayo** [comment]
@fortis do you have the same problem with the docker hub? Is it an intermittent problem, or you cannot push to Tutum registry no matter how many times you try?

**Comment by fermayo** [comment]
This seems like a temporary network issue - closing

**Comment by fortis** [comment]
still exists:
![](http://3xff.net/y6cud25040011.jpg)

**Comment by fermayo** [comment]
can you push to other registries?

**Comment by johnstontrav** [comment]
I too am getting the same error.

![screen shot 2015-05-19 at 12 50 46 pm](https://cloud.githubusercontent.com/assets/7200330/7694582/ba8e5962-fe25-11e4-91f0-9d56dc8636d0.png)

**Comment by revett** [comment]
I can push to the Docker registry and the private registry at work.

**Comment by joda70** [comment]
Could you please tell me how you solved the problem. I have the same problem.

**Comment by fermayo** [comment]
There are several different issues in this thread:
1. `500 Server Error: Internal Server Error ("Server Error: Post https://tutum.co/v1/users/: EOF")` which was the original issue, which has been fixed a long time ago
2. `Error response from daemon: v1 ping attempt failed with error: Get https://tutum.co/v1/_ping: dial tcp: i/o timeout.` which should be a temporary network issue between the docker daemon and our registry - retrying should fix it
3. `404 Client Error: Not Found ("b1 ping attempt failed with error: Get https://tutum.co/v1/_ping: dial tcp: lookup tutum.co: no such host` which should be a temporary DNS resolution issue and should also be solved by just retrying

**In order to debug if the above happens even when retrying:**
* For problem 2), it will help to get the output of `curl -v https://tutum.co/v1/_ping`
* For problem 3), it will help to get the output of `dig tutum.co; dig +trace tutum.co`

Thanks!

**Comment by johnhamelink** [comment]
@fermayo I'm having issue 2 as you've described (`v1 ping attempt failed with error`). Here's what happens when I run `curl -v https://tutum.co/v1/_ping`:

```
[john:~] 1 % curl -v https://tutum.co/v1/_ping
*   Trying 54.85.213.230...
* Connected to tutum.co (54.85.213.230) port 443 (#0)
* ALPN, offering http/1.1
* Cipher selection: ALL:!EXPORT:!EXPORT40:!EXPORT56:!aNULL:!LOW:!RC4:@STRENGTH
* successfully set certificate verify locations:
*   CAfile: /etc/ssl/certs/ca-certificates.crt
  CApath: none
* TLSv1.2, TLS Unknown, Unknown (22):
* TLSv1.2, TLS handshake, Client hello (1):
* SSLv2, Unknown (22):
* TLSv1.2, TLS handshake, Server hello (2):
* SSLv2, Unknown (22):
* TLSv1.2, TLS handshake, CERT (11):
* SSLv2, Unknown (22):
* TLSv1.2, TLS handshake, Server key exchange (12):
* SSLv2, Unknown (22):
* TLSv1.2, TLS handshake, Server finished (14):
* SSLv2, Unknown (22):
* TLSv1.2, TLS handshake, Client key exchange (16):
* SSLv2, Unknown (20):
* TLSv1.2, TLS change cipher, Client hello (1):
* SSLv2, Unknown (22):
* TLSv1.2, TLS handshake, Finished (20):
* SSLv2, Unknown (20):
* TLSv1.2, TLS change cipher, Client hello (1):
* SSLv2, Unknown (22):
* TLSv1.2, TLS handshake, Finished (20):
* SSL connection using TLSv1.2 / ECDHE-RSA-AES128-GCM-SHA256
* ALPN, server did not agree to a protocol
* Server certificate:
* 	 subject: OU=Domain Control Validated; OU=EssentialSSL Wildcard; CN=*.tutum.co
* 	 start date: 2014-11-10 00:00:00 GMT
* 	 expire date: 2015-11-11 23:59:59 GMT
* 	 subjectAltName: tutum.co matched
* 	 issuer: C=GB; ST=Greater Manchester; L=Salford; O=COMODO CA Limited; CN=COMODO RSA Domain Validation Secure Server CA
* 	 SSL certificate verify ok.
* SSLv2, Unknown (23):
> GET /v1/_ping HTTP/1.1
> Host: tutum.co
> User-Agent: curl/7.42.1
> Accept: */*
> 
* SSLv2, Unknown (23):
< HTTP/1.1 200 OK
< Cache-Control: no-cache
< Content-Type: application/json
< Date: Sun, 31 May 2015 13:10:41 GMT
< Expires: -1
< Pragma: no-cache
< Server: nginx/1.4.6 (Ubuntu)
< X-Docker-Registry-Config: prod
< X-Docker-Registry-Standalone: True
< X-Docker-Registry-Version: 0.8.1
< X-Sentry-ID: None
< Content-Length: 4
< Connection: keep-alive
< 
* Connection #0 to host tutum.co left intact
true% 
```

**Comment by johnstontrav** [comment]
Those using boot2docker....i had success with this:

```
boot2docker ssh
echo "nameserver 8.8.8.8" > /etc/resolv.conf && sudo /etc/init.d/docker restart
```

**Comment by codewithpassion** [comment]
For those with the login issue, moving to the google nameserver (8.8.8.8) solved that for me.

**Comment by donovanmuller** [comment]
@codewithpassion  +1 on using Google nameserver solution

Same error as @fortis @johnstontrav
Resolution:
- added `--insecure-registry tutum.co` to `DOCKER_OPTS` in `/etc/default/docker`
- restarted docker
- added Google nameserver (for Ubuntu based distros see [here](http://unix.stackexchange.com/a/154538))

pushing worked as expected with tutum cli and docker cli.

**Comment by claudio-dalicandro** [comment]
+1, Seems that I can't solve even with the solution proposed by @donovanmuller...

**Comment by vdaniuk** [comment]
I'm experiencing a similar error:

```
unable to ping registry endpoint https://tutum.com/v0/
v2 ping attempt failed with error: Get https://tutum.com/v2/: x509: certificate is valid for *.server-home.net, server-home.net, not tutum.com
 v1 ping attempt failed with error: Get https://tutum.com/v1/_ping: x509: certificate is valid for *.server-home.net, server-home.net, not tutum.com
```

Added insecure registry to docker options to no avail.

**Comment by michelzanini** [comment]
This fails to me all the time:

The push refers to a repository [tutum.co/michelzanini/abc] (len: 1)
unable to ping registry endpoint https://tutum.co/v0/
v2 ping attempt failed with error: Get https://tutum.co/v2/: dial tcp: lookup tutum.co: no such host
 v1 ping attempt failed with error: Get https://tutum.co/v1/_ping: dial tcp: lookup tutum.co: no such host

Even after adding nameserver 8.8.8.8 to /etc/resolv.conf

**Comment by iujlaki** [comment]
I had problems with my router and after reboot my dev machine it works again.
