### ISSUE TITLE
Python error when using build command

### ISSUE THREAD

**Issue by JStumpp** [tutumcloud/tutum-cli#57]
The following command

    tutum build --tag quickstart-go .

results in the following error

    'module' object has no attribute 'spawn'

Environment: Windows 7, Python 2.7.9

**Comment by tifayuki** [comment]
We are using `distutils.spawn.find_executable("docker")` to find out the docker location. It seems that `spawn` cannot be found  in module `distutils` on python2 on windows.
 
Thank you for reporting this

**Comment by tifayuki** [comment]
It has been fixed in the latest version 0.13.0
