### ISSUE TITLE
EVERY_NODE is an invalid choice

### ISSUE THREAD

**Issue by pierredavidbelanger** [tutumcloud/tutum-cli#58]
I am trying to create a service with `--deployment-strategy EVERY_NODE`

I get the error:
`tutum service create: error: argument --deployment-strategy: invalid choice: 'EVERY_NODE' (choose from 'EMPTIEST_NODE', 'HIGH_AVAILABILITY', 'EVERY_NODE ')`

Some infos:
```
$ tutum -v
tutum 0.11.5.1
$ uname -v
Darwin Kernel Version 14.1.0: Mon Dec 22 23:10:38 PST 2014; root:xnu-2782.10.72~2/RELEASE_X86_64
```

**Comment by tifayuki** [comment]
Thank you for reporting this. I will fix it ASAP
