### ISSUE TITLE
Specify containers by container name and stack name

### ISSUE THREAD

**Issue by ianneub** [tutumcloud/tutum-cli#61]
It would be awesome to be able to specify containers with this syntax:

`tutum exec web-1.devops-web`

Where `web-1` is the name of the container, in the `web` service, in the `devops-web` stack. Currently, because I have many `web-1` container names I have to use the UUID.

**Comment by tifayuki** [comment]
Yes, the api support the lookup like `https://dashboard.tutum.co/api/v1/container/?name=web-1&service__stack__name=quickstart-python`

So it is possible to do it, I think.
Will implement it in the next version

**Comment by tifayuki** [comment]
fixed in 0.15.1

Should be about to do `tutum exec stack-name.container-name`

**Comment by xiphiaz** [comment]
Note that the command order is actually `tutum exec container-name.stack-name` in latest (0.21.0)

**Comment by tifayuki** [comment]
True. The order is changed. Thank you for pointing out this
